version: 2
defaults:
  branch: main
branches:
  - main
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - requirements: docs/requirements.txt
