version: 2
default_branch: main
branches:
  - main
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
build:
  clean: true
  no_local: true
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - requirements: docs/requirements.txt
